
modLoader="javafml" #mandatory

loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="ARR"
[[mods]] #mandatory

modId="fastpaintings" #mandatory
version = "${version}"
displayName="Fast Paintings" #mandatory
logoFile="icon.png" #optional
authors="MehVahdJukaar" #optional

description='''Makes paintings way faster by turning them into blocks! Also allows customizing their model'''

displayURL="https://www.curseforge.com/minecraft/mc-mods/fast-paintings" #optional
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/fastpaintings/issues" #optional
itemIcon="minecraft:painting" #catalogue icon


[[dependencies.fastpaintings]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.fastpaintings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastpaintings]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.19-2.2.0,)"
    ordering="NONE"
    side="BOTH"
